# Generated by Django 2.2 on 2020-05-02 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='город')),
                ('source', models.URLField(blank=True, max_length=1000, null=True, verbose_name='ссылка на ресурс')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(20, message='Введите Ваше имя')], verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(message='Введите коректный адрес электронной почты')], verbose_name='Электронная почта')),
                ('text', models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500, message='Допустимое количество символов привысило 500'), django.core.validators.MinLengthValidator(0, message='Введите сообщение')], verbose_name='Текст сообщения')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('icon', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ссылка на картинку')),
                ('description', models.TextField(blank=True, editable=False, null=True, verbose_name='Текст новости')),
                ('url_source', models.URLField(blank=True, max_length=1000, null=True, verbose_name='ссылка на ресурс')),
                ('media', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на медиа')),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='news.Category', verbose_name='Категория')),
                ('city', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='news.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-published'],
            },
        ),
    ]
