# Generated by Django 2.2 on 2020-05-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='city',
        ),
        migrations.CreateModel(
            name='CityNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('icon', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ссылка на картинку')),
                ('description', models.TextField(blank=True, editable=False, null=True, verbose_name='Текст новости')),
                ('url_source', models.URLField(blank=True, max_length=1000, null=True, verbose_name='ссылка на ресурс')),
                ('media', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на медиа')),
                ('city', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='news.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-published'],
            },
        ),
    ]
