# Generated by Django 2.2 on 2020-05-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200504_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citynews',
            options={'ordering': ['-published'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости регионов'},
        ),
    ]
