# Generated by Django 2.2 on 2020-05-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200505_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('day', models.IntegerField(verbose_name='день')),
                ('month', models.IntegerField(verbose_name='месяц')),
                ('year', models.IntegerField(verbose_name='год')),
                ('hour', models.IntegerField(verbose_name='час')),
                ('weekday', models.CharField(max_length=200, verbose_name='день недели')),
                ('cloudiness', models.CharField(max_length=30, verbose_name='облачность')),
                ('precipitation', models.CharField(max_length=30, verbose_name='осадки')),
                ('pressure_min', models.CharField(max_length=30, verbose_name='минимальное давление')),
                ('pressure_max', models.CharField(max_length=30, verbose_name='максимальное давление')),
                ('wind_min', models.CharField(max_length=30, verbose_name='мин скорость ветра')),
                ('wind_max', models.CharField(max_length=30, verbose_name='макс скорость ветра')),
                ('wind_direction', models.CharField(max_length=30, verbose_name='направление ветра')),
                ('humidity_min', models.CharField(max_length=30, verbose_name='мин влажность')),
                ('humidity_max', models.CharField(max_length=30, verbose_name='макс влажность')),
                ('heat_min', models.CharField(max_length=30, verbose_name='мин температура ощущаемая')),
                ('heat_max', models.CharField(max_length=30, verbose_name='макс температура ощущаемая')),
                ('temperature_min', models.CharField(max_length=30, verbose_name='минимальная температура')),
                ('temperature_max', models.CharField(max_length=30, verbose_name='максимальная температура')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.City', verbose_name='город')),
            ],
            options={
                'verbose_name': 'погода',
                'ordering': ['-published'],
            },
        ),
    ]
