# Generated by Django 2.2 on 2020-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200603_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='month',
            field=models.CharField(max_length=20, verbose_name='месяц'),
        ),
    ]
